{
 "title": "Personal Finance",
 "description": "Personal Finance for Phil and Steph\n",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "account name",
    "query": "select distinct account_name from reporting__fresh_table\n"
   },
   {
    "name": "subcategory_name",
    "label": "Subcategory Name",
    "query": "select distinct subcategory from reporting.reporting__fact_transactions \norder by subcategory"
   },
   {
    "name": "category_name",
    "label": "Category Name",
    "query": "select distinct category from reporting.reporting__fact_transactions \norder by category"
   }
  ]
 },
 "panels": [
  {
   "title": "Balance by Year/Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select year_month, ${account_name:csv}\r\nfrom reporting__pivot_last_balance\r\nwhere year_month between $__timeFrom() and $__timeTo()"
    }
   ]
  },
  {
   "title": "Credit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\nTO_CHAR(date, 'YYYY-MM') as date,\r\nsum(amount) as credit\r\nfrom reporting__fact_transactions\r\nwhere account_name in ($account_name)\r\nand $__timeFilter(date) \r\nand amount_type = 'CREDIT'\r\nand category in (${category_name}) \r\nand subcategory in (${subcategory_name})\r\ngroup by \r\n1\r\norder by \r\n1\r\n"
    }
   ]
  },
  {
   "title": "Net Position After Homeloan",
   "type": "barchart",
   "description": "Excluding Shares",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT *\r\n FROM reporting__monthly_balances_yoy\r\n where year_month between $__timeFrom() and $__timeTo() \r\n "
    }
   ]
  },
  {
   "title": "Debit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\nTO_CHAR(date, 'YYYY-MM') as date,\r\nsum(amount) as debit\r\nfrom reporting__fact_transactions\r\nwhere account_name in ($account_name)\r\nand $__timeFilter(date) \r\nand amount_type = 'DEBIT'\r\nand category in (${category_name}) \r\nand subcategory in (${subcategory_name})\r\ngroup by \r\n1\r\norder by \r\n1\r\n"
    }
   ]
  },
  {
   "title": "MoM Differences",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM reporting__monthly_differences\nwhere year_month between $__timeFrom() and $__timeTo() "
    }
   ]
  }
 ]
}