{
 "title": "Personal Finance - Transactions",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "amount_type",
    "label": "Debit/Credit",
    "query": "select distinct amount_type from reporting.reporting__fact_transactions"
   },
   {
    "name": "account_code",
    "label": "Account Code",
    "query": "select distinct origin_key from reporting.dim_account"
   },
   {
    "name": "account_name",
    "label": "Account",
    "query": "select distinct account_name from reporting.dim_account"
   },
   {
    "name": "bank_name",
    "label": "Bank",
    "query": "select distinct bank_name from reporting.dim_account"
   },
   {
    "name": "category_name",
    "label": "Category",
    "query": "select distinct category from reporting.dim_category"
   },
   {
    "name": "subcategory_name",
    "label": "Subcategory",
    "query": "select distinct subcategory from reporting.dim_category"
   },
   {
    "name": "store_name",
    "label": "Store",
    "query": "select distinct store from reporting.dim_category"
   },
   {
    "name": "internal_indicator",
    "label": "Internal / External Trans",
    "query": "select distinct internal_indicator from reporting.dim_category"
   }
  ]
 },
 "panels": [
  { "title": "Spend by Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concentration of Spend",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    cast(EXTRACT(YEAR FROM trans.date) as text) AS year,\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Jan') AS \"Jan\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Feb') AS \"Feb\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Mar') AS \"Mar\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Apr') AS \"Apr\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'May') AS \"May\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Jun') AS \"Jun\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Jul') AS \"Jul\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Aug') AS \"Aug\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Sep') AS \"Sep\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Oct') AS \"Oct\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Nov') AS \"Nov\",\r\n    SUM(trans.amount) FILTER (WHERE cal.month_short = 'Dec') AS \"Dec\"\r\nFROM\r\n    \"personal_finance\".\"reporting\".\"reporting__fact_transactions\"  as trans\r\n    left join reporting.dim_category as cat\r\n        on trans.category_foreign_key = cat.origin_key\r\n    left join reporting.dim_account as acc\r\n        on trans.account_foreign_key = acc.origin_key\r\n    LEFT JOIN reporting.date_calendar as cal \r\n        on trans.date = cal.date\r\nWHERE\r\n  trans.date between $__timeFrom() and $__timeTo()\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\nGROUP BY\r\n    1\r\nORDER BY\r\n    1\r\n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\n    TO_CHAR(trans.date, 'YYYY-MM') as \"Year Month\",\r\n    sum(trans.amount) as \"Transaction Amount\"\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  date between $__timeFrom() and $__timeTo()\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n\r\ngroup by\r\n    TO_CHAR(trans.date, 'YYYY-MM')\r\n"
    }
   ]
  },
  { "title": "Spend by Category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Category Spend",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\n    cat.category as \"Category\",\r\n    sum(trans.amount) as \"Transaction Amount\"\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  EXTRACT(YEAR FROM trans.date) = EXTRACT(YEAR FROM CURRENT_DATE)\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n\r\ngroup by\r\n    cat.category\r\norder by\r\n    cat.category\r\n"
    }
   ]
  },
  {
   "title": "Subcategory Spend",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\n    cat.subcategory as \"Subcategory\",\r\n    sum(trans.amount) as \"Transaction Amount\"\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  EXTRACT(YEAR FROM trans.date) = EXTRACT(YEAR FROM CURRENT_DATE)\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n\r\ngroup by\r\n    cat.subcategory\r\norder by\r\n    cat.subcategory\r\n"
    }
   ]
  },
  {
   "title": "Store Spend",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\n    cat.store as \"Store\",\r\n    sum(trans.amount) as \"Transaction Amount\"\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  EXTRACT(YEAR FROM trans.date) = EXTRACT(YEAR FROM CURRENT_DATE)\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n\r\ngroup by\r\n    cat.store\r\norder by\r\n    cat.store\r\n"
    }
   ]
  },
  {
   "title": "Transactions as Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions as Table",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "rawSql": "select \r\ntrans.date,\r\ntrans.amount,\r\ntrans.memo,\r\ncat.category,\r\ncat.subcategory,\r\ncat.store,\r\ncat.internal_indicator\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  date between $__timeFrom() and $__timeTo()\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Amount Type (Credit and Debit Split into Two Graphs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "amount_type"
  },
  {
   "title": "Transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \r\n    TO_CHAR(trans.date, 'YYYY-MM') as \"Year Month\",\r\n    sum(trans.amount) as \"Transaction Amount\"\r\nfrom reporting.reporting__fact_transactions as trans\r\nleft join reporting.dim_category as cat\r\n    on trans.category_foreign_key = cat.origin_key\r\nleft join reporting.dim_account as acc\r\n    on trans.account_foreign_key = acc.origin_key\r\n\r\nWHERE\r\n  date between $__timeFrom() and $__timeTo()\r\n  and trans.amount_type in ($amount_type)\r\n  and account_foreign_key in ($account_code)\r\n  and acc.account_name in ($account_name)\r\n  and acc.bank_name in ($bank_name)\r\n  and cat.category in ($category_name)\r\n  and cat.subcategory in ($subcategory_name)\r\n  and cat.store in ($store_name)\r\n  and cat.internal_indicator in ($internal_indicator)\r\n\r\ngroup by\r\n    TO_CHAR(trans.date, 'YYYY-MM')\r\n"
    }
   ]
  }
 ]
}