# ./dockerfile

FROM python:3.11-slim

# Environment variables
ENV DAGSTER_HOME=/docker/appdata/dagster/dagster_home/
ENV DAGSTER_APP=/docker/appdata/dagster


# RUN rm /var/lib/postgresql/data

# Create application directory
WORKDIR ${DAGSTER_APP}

COPY pyproject.toml ./

# Install the required dependencies
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --without dev


WORKDIR ${DAGSTER_APP}

# Create Dagster home directory
RUN mkdir -p ${DAGSTER_HOME}
COPY workspace.yaml dagster.yaml  ${DAGSTER_HOME}/
