FROM postgres:16

# Copy the custom entrypoint script
COPY custom_entrypoint.sh /docker-entrypoint-initdb.d/

# Make sure the script is executable
RUN chmod +x  /docker-entrypoint-initdb.d/custom_entrypoint.sh

# Default command to be executed
CMD ["postgres"]