FROM postgres:16

# Copy the custom entrypoint script
COPY custom_entrypoint.sh /usr/local/bin/

# Make sure the script is executable
RUN chmod +x /usr/local/bin/custom_entrypoint.sh

# Set the script to be the entrypoint
ENTRYPOINT ["/usr/local/bin/custom_entrypoint.sh"]

# Default command to be executed
CMD ["postgres"]