
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'personal_finance'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'personal_finance'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  personal_finance:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +schema: staging
      +materialized: table
    transformation:
      enabled: true
      +schema: transformation
      +materialized: table
    marts:
      enabled: true
      +schema: reporting
      +materialized: table
    reporting:
      enabled: true
      +schema: reporting
      +materialized: table
      projections:
        +schema: reporting
        +materialized: table
    viz:
      enabled: true
      +schema: reporting
      +materialized: table

seeds:
  schema: landing
  personal_finance:
    local:
      +enabled: "{{ target.name == 'local_duckdb' }}"
    banking_categories:
      +column_types:
        transaction_description: text
        transaction_type: text
        sender: text
        recipient: text
        account_name: text
        category: text
        subcategory: text

vars:
  # Defaults for suggestion models
  high_value_threshold: 200               # lower than 1000 to surface more groups
  suggestion_confidence_min: 0.4          # allow medium-confidence suggestions
  suggestion_support_min: 1               # accept suggestions seen once

on-run-start:
  - >
      {% if target.type == 'duckdb' %}
      CREATE OR REPLACE MACRO to_char(val, fmt) AS (
        CASE
          WHEN fmt = 'YYYY-MM' THEN strftime(CAST(val AS TIMESTAMP), '%Y-%m')
          WHEN fmt = 'YYYY-MM-DD' THEN strftime(CAST(val AS TIMESTAMP), '%Y-%m-%d')
          WHEN fmt = 'YYYY' THEN strftime(CAST(val AS TIMESTAMP), '%Y')
          WHEN fmt LIKE 'FM%' THEN CAST(val AS VARCHAR)
          ELSE CAST(val AS VARCHAR)
        END
      );
      CREATE OR REPLACE MACRO to_date(val, fmt) AS (
        CASE
          WHEN fmt = 'YYYY-MM' THEN CAST(strptime(val, '%Y-%m') AS DATE)
          WHEN fmt = 'YYYY-MM-DD' THEN CAST(strptime(val, '%Y-%m-%d') AS DATE)
          WHEN fmt = 'YYYY' THEN CAST(strptime(val, '%Y') AS DATE)
          ELSE CAST(strptime(val, '%Y-%m-%d') AS DATE)
        END
      );
      CREATE OR REPLACE MACRO to_timestamp(val, fmt) AS (
        CASE
          WHEN fmt = 'YYYY-MM' THEN strptime(val || '-01', '%Y-%m-%d')
          WHEN fmt = 'YYYY-MM-DD' THEN strptime(val, '%Y-%m-%d')
          WHEN fmt = 'YYYY' THEN strptime(val || '-01-01', '%Y-%m-%d')
          ELSE strptime(val, '%Y-%m-%d')
        END
      );
      {% endif %}
