personal_finance:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DAGSTER_POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('DAGSTER_POSTGRES_USER', 'dagster_service') }}"
      password: "{{ env_var('DAGSTER_POSTGRES_PASSWORD', '') }}"
      port: "{{ env_var('DAGSTER_POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('DAGSTER_POSTGRES_DB', 'personal_finance') }}"
      schema: landing
    test:
      type: postgres
      host: "{{ env_var('DAGSTER_POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('DAGSTER_POSTGRES_USER', 'dagster_service') }}"
      password: "{{ env_var('DAGSTER_POSTGRES_PASSWORD', '') }}"
      port: "{{ env_var('DAGSTER_POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('DAGSTER_POSTGRES_DB', 'personal_finance') }}"
      schema: landing
