personal_finance:
  target: prod
  outputs:
    prod:
      type: postgres
      host: dagster_postgres
      user: postgres
      password: test
      port: 5432
      dbname: personal_finance
      schema: landing
