personal_finance:
  target: prod
  outputs:
    prod:
      type: postgres
      host: 192.168.1.103
      user: postgres
      password: test
      port: 5432
      dbname: personal_finance
      schema: landing
    test:
      type: postgres
      host: localhost
      user: postgres
      password: test
      port: 5432
      dbname: personal_finance
      schema: landing
