# Use an official Python runtime as a parent image
FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

ARG DAGSTER_APP

ENV YOUR_ENV=${YOUR_ENV} \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  # Copy from the cache instead of linking since it's a mounted volume
  UV_LINK_MODE=copy \ 
  # Enable bytecode compilation
  UV_COMPILE_BYTECODE=1 \ 
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # Make sure to update it!
  DAGSTER_APP=${DAGSTER_APP:-appnotset} \
  PATH="${DAGSTER_APP}/.venv/bin:$PATH"

WORKDIR ${DAGSTER_APP}

COPY uv.lock uv.lock
COPY pyproject.toml pyproject.toml
COPY ha_backup ha_backup

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --package ha_backup

# Expose the port that Dagster gRPC server uses
EXPOSE 4000

# Set the working directory to where the service needs to be started from
WORKDIR ${DAGSTER_APP}

RUN chmod -R +x ${DAGSTER_APP}

# Command to run the Dagster gRPC server
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "ha_backup"]
