version: 2

sources:
  - name: personalfinance_dagster
    schema: landing
    database: personal_finance
    tables:
      - name: ING_BillsBillsBills_Transactions
        meta:
          dagster:
            asset_key: ["ING_BillsBillsBills_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null

      - name: ING_Countdown_Transactions
        meta:
          dagster:
            asset_key: ["ING_Countdown_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null

      - name: Adelaide_Offset_Transactions
        meta:
          dagster:
            asset_key: ["Adelaide_Offset_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null

      - name: Adelaide_Homeloan_Transactions
        meta:
          dagster:
            asset_key: ["Adelaide_Homeloan_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null

      - name: Bendigo_Offset_Transactions
        meta:
          dagster:
            asset_key: ["Bendigo_Offset_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null
      - name: Bendigo_Homeloan_Transactions
        meta:
          dagster:
            asset_key: ["Bendigo_Homeloan_Transactions"]
        columns:
          - name: primary_key
            tests:
              - unique
              - not_null

models:
  - name: staging__Adelaide_Homeloan
  - name: staging__Adelaide_Offset
  - name: staging__Bendigo_Homeloan
  - name: staging__Bendigo_Offset
  - name: staging__ING_billsbillsbills
  - name: staging__ING_countdown

