# Use an official Python runtime as a parent image
FROM python:3.11

# Environment variables
ENV PERSONAL_FINANCE_DASHBOARD=/opt/personal_finance_dashboard

RUN mkdir -p $PERSONAL_FINANCE_DASHBOARD

# Set the working directory in the container
WORKDIR $PERSONAL_FINANCE_DASHBOARD

# Install Poetry
RUN pip install poetry

RUN poetry config virtualenvs.create false

# Copy the pyproject.toml and poetry.lock files
COPY pyproject.toml poetry.lock ./

# Install all dependencies including dbt
RUN poetry install --no-root

# Verify dbt is installed and accessible
RUN which dbt
RUN dbt --version

# Copy the rest of your application code
COPY . .

WORKDIR $PERSONAL_FINANCE_DASHBOARD/dbt_finance

# Run dbt setup commands
RUN dbt deps
RUN dbt seed

WORKDIR $PERSONAL_FINANCE_DASHBOARD

# Expose the port that Dagster dev server uses
EXPOSE 3000

# Run command to start up the dagster development environment
CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
