# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the Docker image
WORKDIR /docker/appdata/dagster/pipeline_personal_finance

COPY . .

# Install the required dependencies
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install
RUN poetry run pip install rpds

WORKDIR /docker/appdata/dagster/pipeline_personal_finance/dbt_finance

RUN sleep infinity

RUN poetry run dbt deps
RUN poetry run dbt build

# Set the working directory to where the service needs to be started from
WORKDIR /docker/appdata/dagster

# Expose the port that Dagster gRPC server uses
EXPOSE 4000


# Command to run the Dagster gRPC server
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "pipeline_personal_finance"]

