WITH RANKEDBALANCES AS (
    SELECT
        account_name,
        CATEGORY,
        SUBCATEGORY,
        DATE,
        ADJUSTED_BALANCE,
        -- Calculate the maximum date for each period
        MAX(DATE) OVER (PARTITION BY account_name, EXTRACT(YEAR FROM DATE)) AS MAX_DATE_YEAR,
        MAX(DATE) OVER (PARTITION BY account_name, EXTRACT(YEAR FROM DATE), EXTRACT(QUARTER FROM DATE)) AS MAX_DATE_QUARTER,
        MAX(DATE) OVER (PARTITION BY account_name, EXTRACT(YEAR FROM DATE), EXTRACT(MONTH FROM DATE)) AS MAX_DATE_MONTH,
        MAX(DATE) OVER (PARTITION BY account_name, EXTRACT(YEAR FROM DATE), EXTRACT(WEEK FROM DATE)) AS MAX_DATE_WEEK,
        MAX(DATE) OVER (PARTITION BY account_name, EXTRACT(YEAR FROM DATE), EXTRACT(MONTH FROM DATE), EXTRACT(DAY FROM DATE)) AS MAX_DATE_DAY
    FROM
        {{ ref("trans_no_int_transfers") }}
)

SELECT
    account_name,
    CATEGORY,
    SUBCATEGORY,
    DATE AS PERIODSTART,
    ADJUSTED_BALANCE AS LATESTBALANCE,
    CASE
        WHEN DATE = MAX_DATE_DAY THEN 'Day'
        WHEN DATE = MAX_DATE_WEEK THEN 'Week'
        WHEN DATE = MAX_DATE_MONTH THEN 'Month'
        WHEN DATE = MAX_DATE_QUARTER THEN 'Quarter'
        WHEN DATE = MAX_DATE_YEAR THEN 'Year'
        -- For safety, though each row should fit one of the above categories
    END AS PERIODTYPE
FROM
    RANKEDBALANCES
WHERE
    DATE = MAX_DATE_DAY 
    OR DATE = MAX_DATE_WEEK 
    OR DATE = MAX_DATE_MONTH 
    OR DATE = MAX_DATE_QUARTER 
    OR DATE = MAX_DATE_YEAR
