version: 2
models:
  - name: int_adel_homeloan_adjst_bal
    description: Adjusts the balance based on known values provided in the seed tables.
    columns:
      - name: receipt
        data_type: text
      - name: location
        data_type: text
      - name: description_date
        data_type: text
      - name: card_no
        data_type: text
      - name: sender
        data_type: text
      - name: recipient
        data_type: text
      - name: transaction_amount
        data_type: double precision
      - name: line_number
        data_type: bigint
      - name: primary_key
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: account_name
        data_type: text
      - name: transaction_date
        data_type: date
      - name: memo
        data_type: text
      - name: transaction_description
        data_type: text
      - name: transaction_type
        data_type: text
      - name: etl_date
        data_type: date
      - name: etl_time
        data_type: time with time zone
      - name: transaction_balance
        data_type: numeric
      - name: adjusted_transaction_balance
        data_type: numeric
        tests:
          - accepted_values:
              values: [ -564089.65 ]
              config:
                where: "transaction_date = '2023-06-24' and account_name = 'Adelaide_Homeloan'"

  - name: int_adel_offset_adjst_bal
    columns:
      - name: transaction_date
        data_type: date
      - name: memo
        data_type: text
      - name: receipt
        data_type: text
      - name: location
        data_type: text
      - name: description_date
        data_type: text
      - name: card_no
        data_type: text
      - name: sender
        data_type: text
      - name: recipient
        data_type: text
      - name: transaction_description
        data_type: text
      - name: transaction_type
        data_type: text
      - name: transaction_amount
        data_type: double precision
      - name: line_number
        data_type: bigint
      - name: primary_key
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: etl_date
        data_type: date
      - name: etl_time
        data_type: time with time zone
      - name: account_name
        data_type: text
      - name: transaction_balance
        data_type: numeric
      - name: adjusted_transaction_balance
        data_type: numeric
        tests:
          - accepted_values:
              values: [ 106130.73 ]
              config:
                where: "transaction_date = '2023-06-19' and account_name = 'Adelaide_Offset'"

  - name: int_ben_homeloan_adjst_bal
    columns:
      - name: transaction_date
        data_type: date
      - name: memo
        data_type: text
      - name: receipt
        data_type: text
      - name: location
        data_type: text
      - name: description_date
        data_type: text
      - name: card_no
        data_type: text
      - name: sender
        data_type: text
      - name: recipient
        data_type: text
      - name: transaction_description
        data_type: text
      - name: transaction_type
        data_type: text
      - name: transaction_amount
        data_type: double precision
      - name: line_number
        data_type: bigint
      - name: primary_key
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: etl_date
        data_type: date
      - name: etl_time
        data_type: time with time zone
      - name: account_name
        data_type: text
      - name: transaction_balance
        data_type: numeric
      - name: adjusted_transaction_balance
        data_type: numeric
        tests:
          - accepted_values:
              values: [ 0 ]
              config:
                where: "transaction_date = '2024-03-15' and account_name = 'Bendigo_Bank_Homeloan'"

  - name: int_ben_offset_adjst_bal
    columns:
      - name: transaction_date
        data_type: date
      - name: memo
        data_type: text
      - name: receipt
        data_type: text
      - name: location
        data_type: text
      - name: description_date
        data_type: text
      - name: card_no
        data_type: text
      - name: sender
        data_type: text
      - name: recipient
        data_type: text
      - name: transaction_description
        data_type: text
      - name: transaction_type
        data_type: text
      - name: transaction_amount
        data_type: double precision
      - name: line_number
        data_type: bigint
      - name: primary_key
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: etl_date
        data_type: date
      - name: etl_time
        data_type: time with time zone
      - name: account_name
        data_type: text
      - name: transaction_balance
        data_type: numeric
      - name: adjusted_transaction_balance
        data_type: numeric
        tests:
          - accepted_values:
              values: [ 0 ]
              config:
                where: "transaction_date = '2024-01-04' and account_name = 'Bendigo_Bank_Offset'"

  - name: int_ing_bills_adjst_bal
    columns:
      - name: transaction_date
        data_type: date
      - name: transaction_description
        data_type: text
      - name: transaction_type
        data_type: text
      - name: memo
        data_type: text
      - name: receipt
        data_type: text
      - name: location
        data_type: text
      - name: description_date
        data_type: text
      - name: card_no
        data_type: text
      - name: sender
        data_type: text
      - name: recipient
        data_type: text
      - name: transaction_amount
        data_type: double precision
      - name: line_number
        data_type: bigint
      - name: primary_key
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: etl_date
        data_type: date
      - name: etl_time
        data_type: time with time zone
      - name: account_name
        data_type: text
      - name: transaction_balance
        data_type: numeric
      - name: adjusted_transaction_balance
        data_type: numeric
        tests:
          - accepted_values:
              values: [ 1071.94 ]
              config:
                where: "transaction_date = '2023-10-21' and account_name = 'ING_billsbillsbills'"
