#!/usr/bin/env python3
"""Generate deterministic Docker Compose overrides per worktree."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path


DEFAULTS = {
    "COMPOSE_PROJECT_NAME": "qif-personal-finance",
    "DAGSTER_UI_PORT": "3002",
    "GRAFANA_HOST_PORT": "3001",
    "POSTGRES_HOST_PORT": "5433",
    "DAGSTER_UI_BIND_HOST": "127.0.0.1",
    "GRAFANA_BIND_HOST": "127.0.0.1",
    "POSTGRES_BIND_HOST": "127.0.0.1",
    # PIPELINE_IMAGE is intentionally absent from DEFAULTS so the main worktree
    # uses the docker-compose.yml default of "pipeline_personal_finance".
}

PORT_BASES = {
    "DAGSTER_UI_PORT": 32000,
    "GRAFANA_HOST_PORT": 34000,
    "POSTGRES_HOST_PORT": 36000,
}

PORT_RANGE = 1000
MAIN_NAMES = {"qif_personal_finance", "qif-personal-finance"}


def slugify(value: str) -> str:
    chars = []
    last_was_dash = False
    for char in value.lower():
        if char.isalnum():
            chars.append(char)
            last_was_dash = False
            continue
        if not last_was_dash:
            chars.append("-")
            last_was_dash = True
    return "".join(chars).strip("-") or "worktree"


BIND_HOST_KEYS = {"DAGSTER_UI_BIND_HOST", "GRAFANA_BIND_HOST", "POSTGRES_BIND_HOST"}


def _read_env_file(repo_root: Path) -> dict[str, str]:
    """Read key=value pairs from .env in repo_root, ignoring comments."""
    env_path = repo_root / ".env"
    result: dict[str, str] = {}
    if not env_path.exists():
        return result
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip()
    return result


def derive_values(repo_root: Path) -> dict[str, str]:
    worktree_name = repo_root.name
    env_overrides = _read_env_file(repo_root)

    if worktree_name in MAIN_NAMES:
        values = DEFAULTS.copy()
    else:
        digest = hashlib.sha1(str(repo_root).encode("utf-8")).hexdigest()
        offset = int(digest[:8], 16) % PORT_RANGE
        project_name = f"qif-{slugify(worktree_name)}"

        values = DEFAULTS.copy()
        values["COMPOSE_PROJECT_NAME"] = project_name
        for key, base in PORT_BASES.items():
            values[key] = str(base + offset)
        # Each worktree gets its own image tag so builds don't overwrite each other.
        values["PIPELINE_IMAGE"] = f"pipeline_personal_finance-{slugify(worktree_name)}"

    # Allow .env to override bind hosts (e.g. 0.0.0.0 for LAN access).
    for key in BIND_HOST_KEYS:
        if key in env_overrides:
            values[key] = env_overrides[key]

    return values


def format_env(values: dict[str, str], repo_root: Path) -> str:
    lines = [
        "# Auto-generated by scripts/write_worktree_compose_env.py",
        f"# Source worktree: {repo_root}",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=".env.worktree.auto",
        help="Path to the generated env file.",
    )
    parser.add_argument(
        "--print-project-name",
        action="store_true",
        help="Print only the derived Compose project name.",
    )
    args = parser.parse_args()

    repo_root = Path(os.getcwd())
    values = derive_values(repo_root)

    if args.print_project_name:
        print(values["COMPOSE_PROJECT_NAME"])
        return 0

    output_path = Path(args.output)
    output_path.write_text(format_env(values, repo_root), encoding="utf-8")
    print(f"Wrote {output_path} for {repo_root.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
