personal_finance:
  target: local_duckdb
  outputs:
    local_duckdb:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'pipeline_personal_finance/dbt_finance/duckdb/personal_finance.duckdb') }}"
      schema: landing
      threads: 4
