version: 2

models:
  - name: dim_accounts_enhanced
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [account_key]
    columns:
      - name: account_key
        data_type: text
        description: "Surrogate key for the account dimension"
      - name: account_name
        data_type: text
        description: "Name of the account"
      - name: bank_name
        data_type: text  
        description: "Bank that manages the account"
      - name: account_type
        data_type: text
        description: "Type of account (Home Loan, Offset, etc.)"
      - name: account_category
        data_type: text
        description: "Category of account (Asset, Liability)"
      - name: level_1_bank
        data_type: text
        description: "Level 1 of account hierarchy - bank name"
      - name: level_2_category
        data_type: text
        description: "Level 2 of account hierarchy - account category"
      - name: level_3_type
        data_type: text
        description: "Level 3 of account hierarchy - account type"
      - name: level_4_account
        data_type: text
        description: "Level 4 of account hierarchy - account name"
      - name: account_start_date
        data_type: date
        description: "Date of first transaction for this account"
      - name: account_last_transaction_date
        data_type: date
        description: "Date of most recent transaction"
      - name: total_transactions
        data_type: bigint
        description: "Total number of transactions for this account"
      - name: currency_code
        data_type: text
        description: "Currency code for the account"
      - name: is_active
        data_type: boolean
        description: "Whether the account is currently active"
      - name: is_liability
        data_type: boolean
        description: "Whether this account represents a liability"
      - name: is_transactional
        data_type: boolean
        description: "Whether this account supports transactions"
      - name: is_mortgage
        data_type: boolean
        description: "Whether this account is a mortgage account"
      - name: created_at
        data_type: timestamp
        description: "Timestamp when record was created"
      - name: updated_at
        data_type: timestamp
        description: "Timestamp when record was last updated"

  - name: dim_categories_enhanced
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [category_key]
    columns:
      - name: category_key
        data_type: text
        description: "Surrogate key for the category dimension"
      - name: level_1_category
        data_type: text
        description: "Level 1 of category hierarchy"
      - name: level_2_subcategory
        data_type: text
        description: "Level 2 of category hierarchy"
      - name: level_3_store
        data_type: text
        description: "Level 3 of category hierarchy"
      - name: category
        data_type: text
        description: "Original category name"
      - name: subcategory
        data_type: text
        description: "Original subcategory name"
      - name: store
        data_type: text
        description: "Original store name"
      - name: internal_indicator
        data_type: text
        description: "Whether this is an internal or external transaction"
      - name: category_type
        data_type: text
        description: "Type of category (Income, Expense, etc.)"
      - name: is_internal_transfer
        data_type: boolean
        description: "Whether this represents an internal transfer"
      - name: is_income
        data_type: boolean
        description: "Whether this represents income"
      - name: is_financial_service
        data_type: boolean
        description: "Whether this represents a financial service"
      - name: category_priority
        data_type: bigint
        description: "Priority for categorization (lower = higher priority)"
      - name: category_description
        data_type: text
        description: "Description of the category"
      - name: created_at
        data_type: timestamp
        description: "Timestamp when record was created"
      - name: updated_at
        data_type: timestamp
        description: "Timestamp when record was last updated"

  - name: fact_transactions_enhanced
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [transaction_key]
      - type: foreign_key
        columns: [account_key]
        to: ref('dim_accounts_enhanced')
        to_columns: [account_key]
      - type: foreign_key
        columns: [category_key]
        to: ref('dim_categories_enhanced')
        to_columns: [category_key]
    columns:
      - name: transaction_key
        data_type: text
        description: "Surrogate key for the transaction"
      - name: transaction_natural_key
        data_type: text
        description: "Natural key from source system"
      - name: transaction_date
        data_type: date
        description: "Date of the transaction"
      - name: transaction_year
        data_type: bigint
        description: "Year of the transaction"
      - name: transaction_quarter
        data_type: bigint
        description: "Quarter of the transaction"
      - name: transaction_month
        data_type: bigint
        description: "Month of the transaction"
      - name: transaction_day
        data_type: bigint
        description: "Day of the transaction"
      - name: day_of_week
        data_type: bigint
        description: "Day of week (0=Sunday)"
      - name: account_key
        data_type: text
        description: "Foreign key to account dimension"
      - name: category_key
        data_type: text
        description: "Foreign key to category dimension"
      - name: transaction_amount
        data_type: numeric
        description: "Amount of the transaction"
      - name: account_balance
        data_type: numeric
        description: "Account balance after this transaction"
      - name: transaction_direction
        data_type: text
        description: "Direction of transaction (Debit/Credit/Zero)"
      - name: transaction_amount_abs
        data_type: numeric
        description: "Absolute value of transaction amount"
      - name: is_income_transaction
        data_type: boolean
        description: "Whether this is an income transaction"
      - name: is_internal_transfer
        data_type: boolean
        description: "Whether this is an internal transfer"
      - name: is_financial_service
        data_type: boolean
        description: "Whether this is a financial service transaction"
      - name: transaction_memo
        data_type: text
        description: "Transaction memo/description"
      - name: transaction_type
        data_type: text
        description: "Type of transaction"
      - name: transaction_description
        data_type: text
        description: "Full transaction description"
      - name: receipt
        data_type: text
        description: "Receipt information"
      - name: location
        data_type: text
        description: "Transaction location"
      - name: sender
        data_type: text
        description: "Transaction sender"
      - name: recipient
        data_type: text
        description: "Transaction recipient"
      - name: etl_date
        data_type: text
        description: "ETL processing date"
      - name: etl_time
        data_type: text
        description: "ETL processing time"
      - name: fact_created_at
        data_type: timestamp
        description: "Timestamp when fact record was created"

  - name: fact_daily_balances
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [balance_key]
      - type: foreign_key
        columns: [account_key]
        to: ref('dim_accounts_enhanced')
        to_columns: [account_key]
    columns:
      - name: balance_key
        data_type: text
        description: "Surrogate key for the daily balance record"
      - name: balance_date
        data_type: date
        description: "Date of the balance snapshot"
      - name: account_key
        data_type: text
        description: "Foreign key to account dimension"
      - name: account_name
        data_type: text
        description: "Name of the account"
      - name: daily_balance
        data_type: numeric
        description: "Account balance at end of day"
      - name: balance_change
        data_type: numeric
        description: "Change in balance from previous day"
      - name: transaction_count
        data_type: bigint
        description: "Number of transactions on this date"
      - name: total_debits
        data_type: numeric
        description: "Total debit amount for the day"
      - name: total_credits
        data_type: numeric
        description: "Total credit amount for the day"
      - name: is_weekend
        data_type: boolean
        description: "Whether this date falls on a weekend"
      - name: is_month_end
        data_type: boolean
        description: "Whether this is the last day of the month"
      - name: created_at
        data_type: timestamp
        description: "Timestamp when record was created"