version: 2

models:
  - name: fct_daily_balances
    description: "Daily account balance snapshots with transaction summaries"
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [balance_key]
      - type: foreign_key
        columns: [account_key]
        to: ref('dim_accounts')
        to_columns: [account_key]
    columns:
      - name: balance_key
        data_type: text
        description: "Surrogate key for the daily balance record"
      - name: balance_date
        data_type: date
        description: "Date of the balance snapshot"
      - name: account_key
        data_type: text
        description: "Foreign key to account dimension"
      - name: account_name
        data_type: text
        description: "Name of the account"
      - name: daily_balance
        data_type: numeric
        description: "Account balance at end of day"
      - name: balance_change
        data_type: numeric
        description: "Change in balance from previous day"
      - name: transaction_count
        data_type: bigint
        description: "Number of transactions on this date"
      - name: total_debits
        data_type: numeric
        description: "Total debit amount for the day"
      - name: total_credits
        data_type: numeric
        description: "Total credit amount for the day"
      - name: is_weekend
        data_type: boolean
        description: "Whether this date falls on a weekend"
      - name: is_month_end
        data_type: boolean
        description: "Whether this is the last day of the month"
      - name: created_at
        data_type: timestamp
        description: "Timestamp when record was created"

  - name: rpt_outflows_reconciliation_tests
    description: "Per-period reconciliation checks comparing viz outflows to fact aggregates with pass/fail."
    columns:
      - name: period_date
        data_type: date
        description: "Month (first day) the test applies to"
      - name: test_name
        data_type: text
        description: "Identifier for the reconciliation check"
      - name: left_value
        data_type: numeric
        description: "Value from viz_detailed_outflows_breakdown"
      - name: right_value
        data_type: numeric
        description: "Reference value from fact tables"
      - name: delta
        data_type: numeric
        description: "Difference left - right"
      - name: pass
        data_type: boolean
        description: "True when within tolerance"
      - name: notes
        data_type: text
        description: "Short description of what is compared"
      - name: tested_at
        data_type: timestamp
        description: "Timestamp when the row was evaluated"

  - name: rpt_outflows_reconciliation_summary
    description: "Summary of reconciliation results per period with overall PASS/FAIL flag."
    columns:
      - name: period_date
        data_type: date
        description: "Month (first day) being summarized"
      - name: passed
        data_type: bigint
        description: "Number of passing checks"
      - name: failed
        data_type: bigint
        description: "Number of failing checks"
      - name: total
        data_type: bigint
        description: "Total checks for the period"
      - name: status
        data_type: text
        description: "PASS if no failures, else FAIL"
      - name: is_latest
        data_type: boolean
        description: "True for latest month"
      - name: summarized_at
        data_type: timestamp
        description: "Timestamp when summary was computed"

  - name: rpt_financials_reconciliation_tests
    description: "Cross-dashboard reconciliation checks (budget, cash flow, executive, income/expense, outflows)."
    columns:
      - name: period_date
        data_type: date
      - name: domain
        data_type: text
        description: "Test domain: Outflows, Budget, CashFlow, Executive, IncomeExpense"
      - name: test_name
        data_type: text
      - name: left_value
        data_type: numeric
      - name: right_value
        data_type: numeric
      - name: delta
        data_type: numeric
      - name: pass
        data_type: boolean
      - name: notes
        data_type: text

  - name: rpt_financials_reconciliation_summary
    description: "Summary of reconciliation results across all domains per period."
    columns:
      - name: period_date
        data_type: date
      - name: passed
        data_type: bigint
      - name: failed
        data_type: bigint
      - name: total
        data_type: bigint
      - name: status
        data_type: text
