dbt_finance:
  target: dev
  outputs:
    dev:
      type: duckdb
      path:  'C:/Users/Phil/Documents/Projects/personal_finance_dashboard/duckdb/finance.duckdb'
    prod:
      type: postgres
      host: 192.168.1.103
      user: postgres
      password: test
      port: 5000
      dbname: personalfinance
      schema: landing
  
