version: 2

models:
  - name: transformation__Adel_Homeloan_adjst_bal
  - name: transformation__Adel_Offset_adjst_bal
  - name: transformation__Ben_Homeloan_adjst_bal
  - name: transformation__Ben_Offset_adjst_bal
  - name: transformation__ING_bills_adjst_bal
  - name: transformation__ING_countdown_adjst_bal
  
